config/routes.rb
Rails.application.routes.draw do
  get 'segments/add'

  resources :segments
  get "segments/add" => "segments#add"
  resources :criteria
  resources :criteria
  resources :criteria
  resources :operators
  resources :contacts
  get "contacts/get_segmented" => "contacts#get_segmented"

  resources :widgets

  root 'welcome#index'

  namespace :api do 
    namespace :v1 do
      resources :contacts
    end
  end

end

app/models/operator.rb
class Operator < ActiveRecord::Base
end

app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
  before_action :set_operator, only: [:show, :edit, :update, :destroy]

  # GET /operators
  # GET /operators.json
  def index
    @operators = Operator.all
  end

  # GET /operators/1
  # GET /operators/1.json
  def show
  end

  # GET /operators/new
  def new
    @operator = Operator.new
  end

  # GET /operators/1/edit
  def edit
  end

  # POST /operators
  # POST /operators.json
  def create
    @operator = Operator.new(operator_params)

    respond_to do |format|
      if @operator.save
        format.html { redirect_to @operator, notice: 'Operator was successfully created.' }
        format.json { render :show, status: :created, location: @operator }
      else
        format.html { render :new }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operators/1
  # PATCH/PUT /operators/1.json
  def update
    respond_to do |format|
      if @operator.update(operator_params)
        format.html { redirect_to @operator, notice: 'Operator was successfully updated.' }
        format.json { render :show, status: :ok, location: @operator }
      else
        format.html { render :edit }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operators/1
  # DELETE /operators/1.json
  def destroy
    @operator.destroy
    respond_to do |format|
      format.html { redirect_to operators_url, notice: 'Operator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operator
      @operator = Operator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operator_params
      params.require(:operator).permit(:name, :type)
    end
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/views/operators/_form.html.erb
<%= form_for(@operator) do |f| %>
  <% if @operator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operator.errors.count, "error") %> prohibited this operator from being saved:</h2>

      <ul>
      <% @operator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operators/edit.html.erb
<h1>Editing Operator</h1>

<%= render 'form' %>

<%= link_to 'Show', @operator %> |
<%= link_to 'Back', operators_path %>

app/views/operators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Operators</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operators.each do |operator| %>
      <tr>
        <td><%= operator.name %></td>
        <td><%= operator.category %></td>
        <td><%= link_to 'Show', operator %></td>
        <td><%= link_to 'Edit', edit_operator_path(operator) %></td>
        <td><%= link_to 'Destroy', operator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Operator', new_operator_path %>

app/views/operators/new.html.erb
<h1>New Operator</h1>

<%= render 'form' %>

<%= link_to 'Back', operators_path %>

app/views/operators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @operator.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @operator.category %>
</p>

<%= link_to 'Edit', edit_operator_path(@operator) %> |
<%= link_to 'Back', operators_path %>