config/routes.rb
Rails.application.routes.draw do
  get 'segments/add'

  resources :segments
  get "segments/add" => "segments#add"
  resources :criteria
  resources :criteria
  resources :criteria
  resources :operators
  resources :contacts
  get "contacts/get_segmented" => "contacts#get_segmented"

  resources :widgets

  root 'welcome#index'

  namespace :api do 
    namespace :v1 do
      resources :contacts
    end
  end

end

app/models/segment.rb
class Segment < ActiveRecord::Base
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  before_action :set_segment, only: [:show, :edit, :update, :destroy]

  # GET /segments
  # GET /segments.json
  def index
    @segments = Segment.all
  end

  # GET /segments/1
  # GET /segments/1.json
  def show
    @criteria = Criterium.where("segment_id = ?",@segment.id)
  end

  def add
    @segment = Segment.new
  end

  # GET /segments/new
  def new
    @segment = Segment.new
  end

  # GET /segments/1/edit
  def edit
  end

  # POST /segments
  # POST /segments.json
  def create
    @segment = Segment.new(segment_params)

    if @segment.valid?
      @segment.save
      
      for @criterium in params[:criteria] do
        criterium = Criterium.new(name:@criterium[1]['field'], operator_id:@criterium[1]['operator'], value:@criterium[1]['value'], segment_id:@segment.id)
        
        if criterium.valid?
          criterium.save
        end
      end

      respond_to do |format|
        format.html { redirect_to @segment, notice: 'Segment was successfully created.' }
        format.json { render :show, status: :created, location: @segment }
      end
    
    else
      respond_with(segment)
    end

"""    respond_to do |format|
      if @segment.save
        format.html { redirect_to @segment, notice: 'Segment was successfully created.' }
        format.json { render :show, status: :created, location: @segment }
      else
        format.html { render :new }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
"""  end

  # PATCH/PUT /segments/1
  # PATCH/PUT /segments/1.json
  def update
    respond_to do |format|
      if @segment.update(segment_params)
        format.html { redirect_to @segment, notice: 'Segment was successfully updated.' }
        format.json { render :show, status: :ok, location: @segment }
      else
        format.html { render :edit }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segments/1
  # DELETE /segments/1.json
  def destroy
    @segment.destroy
    respond_to do |format|
      format.html { redirect_to segments_url, notice: 'Segment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_segment
      @segment = Segment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def segment_params
      params.require(:segment).permit(:name, :criterium_id)
    end
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/_form.html.erb
<%= form_for(@segment) do |f| %>
  <% if @segment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@segment.errors.count, "error") %> prohibited this segment from being saved:</h2>

      <ul>
      <% @segment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:'form-control' %>
  </div>

  <div class="field">
    Criterios
  </div>

  <div class="actions">
    <%= f.submit "Send", class:'btn btn-primary' %>
  </div>
<% end %>

app/views/segments/add.html.erb
<h1>New segment with criteria</h1>

<%= form_for(@segment) do |f| %>
<% if @segment.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@segment.errors.count, "error") %> prohibited this segment from being saved:</h2>

  <ul>
    <% @segment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :name, value:"Name your custom segment" %><br>
  <%= f.text_field :name, class:"form-control", required:true %>
</div>

<div class="field">
  <h2>Criteria</h2>
  <button class="btn btn-success" onclick="addCriterium()" type="button">New Criterium</button><br>

  <div id="criteria">




  </div>
  <hr>
  <div class="actions">
    <%= f.submit "Send", class:"btn btn-primary" %>
  </div>
  <% end %>

app/views/segments/edit.html.erb
<h1>Editing Segment</h1>

<%= render 'form' %>

<%= link_to 'Show', @segment , class:'btn btn-info' %> |
<%= link_to 'Back', segments_path, class:'btn btn-secondary' %>

app/views/segments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Segments</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Criterium</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @segments.each do |segment| %>
      <tr>
        <td><%= segment.name %></td>
        <td>List of criteria</td>
        <td><%= link_to 'Show', segment, class:'btn btn-info' %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Segment', action: :add %>

app/views/segments/new.html.erb
<h1>New Segment</h1>

<%= render 'form' %>

<%= link_to 'Back', segments_path %>

app/views/segments/show.html.erb
<div class="alert alert-success" role="alert"><%= notice %></div>

<p>
	<strong>Name:</strong>
	<%= @segment.name %>
</p>

<p>
	<strong>Criteria:</strong>
	Lista de critérios
	<table class="table table-striped">
		<thead>
			<td>Field</td>
			<td>Operator</td>
			<td>Value</td>
		</thead>
		<tbody>
			<% @criteria.each do |criteria| %>

				<td><%= criteria.name %></td>
				<td><%= criteria.operator_id %></td>
				<td><%= criteria.value %></td>

			<% end %>
		</tbody>
	</table>
</p>

<%= link_to 'Edit', edit_segment_path(@segment), class:"btn btn-success" %> |
<%= link_to 'Back', segments_path, class:"btn btn-secondary" %>