config/routes.rb
Rails.application.routes.draw do
  get 'segments/add'

  resources :segments
  get "segments/add" => "segments#add"
  resources :criteria
  resources :criteria
  resources :criteria
  resources :operators
  resources :contacts
  get "contacts/get_segmented" => "contacts#get_segmented"

  resources :widgets

  root 'welcome#index'

  namespace :api do 
    namespace :v1 do
      resources :contacts
    end
  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/api/v1/contacts_controller.rb
class Api::V1::ContactsController < Api::V1::BaseController
	
	def index
		contacts = Contact.all
		render json: contacts
	end

	def create
		contact = Contact.create(params[:contact])
		if contact.valid?
			respond_with(contact, :location => api_v1_contact_path(contact))
		else
			respond_with(contact)
		end
	end
  
	def update
		contact = Contact.update(params[:id],params[:contact])
		if contact.valid?
			respond_with(contact, :location => api_v1_contact_path(contact))
		else
			respond_with(contact)
		end
	end

	def show
		contact = Contact.find_by_id(params[:id])
		render json: contact
	end
'''
	def get_segmented

		segment = Segment.where("id = ",params[:citerium])

		criteria = Criterium.where("segment_id = ",segment.id)

		for citerium in criteria
			print criterium
		end
	end
'''

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :age, :uf, :job)
    end


    def get_segmented

      segment = Segment.where("id = ",params[:citerium])

      criteria = Criterium.where("segment_id = ",segment.id)

      for citerium in criteria
        print criterium
      end
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :uf %><br>
    <%= f.text_field :uf, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :job %><br>
    <%= f.text_field :job, class:'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit "Send", class:'btn btn-primary' %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact, class:'btn btn-info' %> |
<%= link_to 'Back', contacts_path, class:'btn btn-secondary' %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Uf</th>
      <th>Job</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.age %></td>
        <td><%= contact.uf %></td>
        <td><%= contact.job %></td>
        <td><%= link_to 'Show', contact, class:'btn btn-info' %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact), class:'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path, class:'btn btn-success' %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path, class:'btn btn-secondary' %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @contact.age %>
</p>

<p>
  <strong>Uf:</strong>
  <%= @contact.uf %>
</p>

<p>
  <strong>Job:</strong>
  <%= @contact.job %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact), class:'btn btn-info' %> |
<%= link_to 'Back', contacts_path, class:'btn btn-secondary' %>